### ISSUE TITLE
TypeError: 'MultiPolygon' object is not iterable

### ISSUE THREAD

**Issue by drdoof2019** [yobeatz/mosaic#5]
```
C:\Users\LENOVO\Desktop\mosaic-main>py mosaic.py
Size of input image: 600px * 900px
Estimated number of tiles: 1875
C:\Users\LENOVO\Desktop\mosaic-main\edges.py:108: FutureWarning: `multichannel` is a deprecated argument name for `gaussian`. It will be removed in version 1.0. Please use `channel_axis` instead.
  img = filters.gaussian(img, sigma=16, truncate=gauss/16, multichannel=True)
Pixel guidelines to chains with sorted points: 0.3s
Calculation of angle matrix: 0.9s
C:\Users\LENOVO\Desktop\mosaic-main\tiles.py:20: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
  if p.type not in ['MultiLineString','LineString', 'GeometryCollection']:
C:\Users\LENOVO\Desktop\mosaic-main\tiles.py:20: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
  if p.type not in ['MultiLineString','LineString', 'GeometryCollection']:
C:\Users\LENOVO\Desktop\mosaic-main\tiles.py:20: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
  if p.type not in ['MultiLineString','LineString', 'GeometryCollection']:
C:\Users\LENOVO\Desktop\mosaic-main\tiles.py:20: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
  if p.type not in ['MultiLineString','LineString', 'GeometryCollection']:
C:\Users\LENOVO\Desktop\mosaic-main\tiles.py:20: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
  if p.type not in ['MultiLineString','LineString', 'GeometryCollection']:
C:\Users\LENOVO\Desktop\mosaic-main\tiles.py:20: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
  if p.type not in ['MultiLineString','LineString', 'GeometryCollection']:
C:\Users\LENOVO\Desktop\mosaic-main\tiles.py:20: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
  if p.type not in ['MultiLineString','LineString', 'GeometryCollection']:
C:\Users\LENOVO\Desktop\mosaic-main\tiles.py:20: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
  if p.type not in ['MultiLineString','LineString', 'GeometryCollection']:
C:\Users\LENOVO\Desktop\mosaic-main\tiles.py:20: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
  if p.type not in ['MultiLineString','LineString', 'GeometryCollection']:
C:\Users\LENOVO\Desktop\mosaic-main\tiles.py:20: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
  if p.type not in ['MultiLineString','LineString', 'GeometryCollection']:
C:\Users\LENOVO\Desktop\mosaic-main\tiles.py:20: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
  if p.type not in ['MultiLineString','LineString', 'GeometryCollection']:
C:\Users\LENOVO\Desktop\mosaic-main\tiles.py:20: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
  if p.type not in ['MultiLineString','LineString', 'GeometryCollection']:
C:\Users\LENOVO\Desktop\mosaic-main\tiles.py:20: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
  if p.type not in ['MultiLineString','LineString', 'GeometryCollection']:
C:\Users\LENOVO\Desktop\mosaic-main\tiles.py:20: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
  if p.type not in ['MultiLineString','LineString', 'GeometryCollection']:
C:\Users\LENOVO\Desktop\mosaic-main\tiles.py:20: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
  if p.type not in ['MultiLineString','LineString', 'GeometryCollection']:
C:\Users\LENOVO\Desktop\mosaic-main\tiles.py:20: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
  if p.type not in ['MultiLineString','LineString', 'GeometryCollection']:
C:\Users\LENOVO\Desktop\mosaic-main\tiles.py:20: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
  if p.type not in ['MultiLineString','LineString', 'GeometryCollection']:
C:\Users\LENOVO\Desktop\mosaic-main\tiles.py:20: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
  if p.type not in ['MultiLineString','LineString', 'GeometryCollection']:
C:\Users\LENOVO\Desktop\mosaic-main\tiles.py:20: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
  if p.type not in ['MultiLineString','LineString', 'GeometryCollection']:
Traceback (most recent call last):
  File "C:\Users\LENOVO\Desktop\mosaic-main\mosaic.py", line 73, in <module>
    polygons_chains = tiles.place_tiles_along_chains(chains, angles_0to180, half_tile, RAND_SIZE, MAX_ANGLE, A0, plot=plot_list)
  File "C:\Users\LENOVO\Desktop\mosaic-main\tiles.py", line 88, in place_tiles_along_chains
    p = fit_in_polygon(p, nearby_polygons)
  File "C:\Users\LENOVO\Desktop\mosaic-main\tiles.py", line 17, in fit_in_polygon
    i_largest = np.argmax([p_i.area for p_i in p])
TypeError: 'MultiPolygon' object is not iterable
```
I did not change or modify anything. I am trying with default photo.
Python version: Python 3.10.7

**Comment by yobeatz** [comment]
Which version of shapely do you use? Have you tried with versions as specified in requirements.txt?

**Comment by drdoof2019** [comment]
> Which version of shapely do you use? Have you tried with versions as specified in requirements.txt?

No because it gives error too..
```
C:\Users\user\Desktop\mosaic-main>pip install shapely==1.7.0
Collecting shapely==1.7.0
  Using cached Shapely-1.7.0.tar.gz (349 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-install-q7oq5ilo\shapely_9fbcd46735a24f749321bd118af2412e\setup.py", line 85, in <module>
          from shapely._buildcfg import geos_version_string, geos_version, \
        File "C:\Users\user\AppData\Local\Temp\pip-install-q7oq5ilo\shapely_9fbcd46735a24f749321bd118af2412e\shapely\_buildcfg.py", line 205, in <module>
          lgeos = CDLL("geos_c.dll")
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
          self._handle = _dlopen(self._name, mode)
      FileNotFoundError: Could not find module 'geos_c.dll' (or one of its dependencies). Try using the full path with constructor syntax.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
