### ISSUE TITLE
multichannel error

### ISSUE THREAD

**Issue by chris1pierce** [yobeatz/mosaic#6]
Hey there, excited to use your code but a bit of a novice. I've gotten the following error that I cant seem to troubleshoot:

Exception has occurred: TypeError
gaussian() got an unexpected keyword argument 'multichannel'
  File "C:\Users\cludg\OneDrive\Desktop\python\mosaic-main\edges.py", line 108, in edges_hed
    img = filters.gaussian(img, sigma=16, truncate=gauss/16, multichannel=True)
  File "C:\Users\cludg\OneDrive\Desktop\python\mosaic-main\mosaic.py", line 60, in <module>
    img_edges = edges.edges_hed(img0, gauss=GAUSS, plot=plot_list)
TypeError: gaussian() got an unexpected keyword argument 'multichannel'

any feedback would be appreciated!

**Comment by JavierCoronel** [comment]
Hi @chris1pierce, have you tried updating your version of `skimage`? try `pip install skimage --update` in your console.
If you get the latest version, you can replace the line 
`img = filters.gaussian(img, sigma=16, truncate=gauss/16, multichannel=True)`
With the following:
`img = filters.gaussian(img, sigma=16, truncate=gauss/16, , channel_axis=2))`

**Comment by chris1pierce** [comment]
Thanks @JavierCoronel, that seemed to fix that issue.

It now returns:

Traceback (most recent call last):
  File "C:\Users\cludg\OneDrive\Desktop\python\mosaic-main\mosaic.py", line 73, in <module>
    polygons_chains = tiles.place_tiles_along_chains(chains, angles_0to180, half_tile, RAND_SIZE, MAX_ANGLE, A0, plot=plot_list)
  File "C:\Users\cludg\OneDrive\Desktop\python\mosaic-main\tiles.py", line 88, in place_tiles_along_chains
    p = fit_in_polygon(p, nearby_polygons)
  File "C:\Users\cludg\OneDrive\Desktop\python\mosaic-main\tiles.py", line 17, in fit_in_polygon
    i_largest = np.argmax([p_i.area for p_i in p])
TypeError: 'MultiPolygon' object is not iterable

Any further input is appreciated.

**Comment by JavierCoronel** [comment]
Hi @chris1pierce. You would need to iterate over the geometries of the polygons, to solve it you can use `for p_i in polygon.geoms` (see [here](https://github.com/JavierCoronel/mosaic_generator/blob/66b00a1c5c9c73cc18ae950108c46ad99dffa954/mosaic/mosaic_tiles.py#L176)). 
But eventually, you would have to do further modifications like these in other parts of the code, I have a working version [here ](https://github.com/JavierCoronel/mosaic_generator) if you want to have a look ;)

**Comment by vladootz** [comment]
Hi, I add a PR to fix all the geoms errors and future-proof for geom_type property
