### ISSUE TITLE
Guide for a complete beginner

### ISSUE THREAD

**Issue by EadwinCZ** [yobeatz/mosaic#7]
Hi, I'm stupid. Could somebody please give me a step by step?
Thank you so much.

**Comment by JavierCoronel** [comment]
Hi @EadwinCZ, 
If you want to run the code with your image, you should start by inserting the path of your image in the following line:
https://github.com/yobeatz/mosaic/blob/21488d78c2239f0a1ee51c2b4f660066ece213f6/mosaic.py#L15
So it looks to smt like:
`fname = r'path/to/your/image.png'` 

Then you can execute the `mosaic.py` script and let it run to see the output.

By the way, I have a modified version of this code with an example in case you want to have a look [here](https://github.com/JavierCoronel/mosaic_generator#usage).

**Comment by EadwinCZ** [comment]
Thanks! Will try.

**Comment by AaronFortG** [comment]
Excuse me, how can I use the HED option @JavierCoronel ? I got this error while running it on the default config.

`[2024-09-10 08:03:50,398][__main__][INFO] - Resolved configuration:
[2024-09-10 08:03:50,399][__main__][INFO] - {'image_path': 'data/logo_fedCat.jpg', 'output_folder': 'data/', 'edge_extraction_method': 'HED', 'tile_size': 10, 'coloring_method': 'original', 'num_colors': None, 'resize_image': False, 'mosaic_height': 10, 'mosaic_width': 10, 'interactive_edge_modification': False, 'save_intermediate_steps': False, 'edges_path': None}
[2024-09-10 08:03:50,399][__main__][INFO] - Starting MosaicGenerator
[2024-09-10 08:03:50,400][__main__.utils.image_handler][INFO] - Loading image
[2024-09-10 08:03:50,448][__main__.edges.edge_extractor][INFO] - Extracting edges of image
Error executing job with overrides: []
Traceback (most recent call last):
  File "C:\Users\schoo\PycharmProjects\mosaic_generator\main.py", line 34, in generate_mosaic
    mosaic.generate_mosaic()
  File "C:\Users\schoo\PycharmProjects\mosaic_generator\mosaic\mosaic_generator.py", line 78, in generate_mosaic
    image_edges = self.edge_extractor.run(image)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\schoo\PycharmProjects\mosaic_generator\edges\edge_extractor.py", line 211, in run
    edges = hed.extract_edges(image)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\schoo\PycharmProjects\mosaic_generator\edges\hed.py", line 130, in extract_edges
    image_edges = run_hed_network(input_image)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\schoo\PycharmProjects\mosaic_generator\edges\hed.py", line 85, in run_hed_network
    network = load_network()
              ^^^^^^^^^^^^^^
  File "C:\Users\schoo\PycharmProjects\mosaic_generator\edges\hed.py", line 47, in load_network
    assert os.path.isfile(
           ^^^^^^^^^^^^^^^
AssertionError: C:\Users\schoo\PycharmProjects\mosaic_generator\edges\deploy.prototxt does not exist, download from source https://github.com/s9xie/hed

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.`

**Comment by JavierCoronel** [comment]
Hi @AaronFortG, you are referring to an error coming from [my modified repo](https://github.com/JavierCoronel/mosaic_generator), feel free to open an issue there :) 

If you want to use the HED option, you'll need to download two files and place them in the edges folder. [See this comment](https://github.com/JavierCoronel/mosaic_generator/issues/1#issuecomment-1650274330) of an issue in that repo.
Let me know if you need additional help.
