### ISSUE TITLE
Numpy Error, Import error

### ISSUE THREAD

**Issue by AKVG** [yobeatz/mosaic#9]
Good evening,

I am attempting to run this script and am getting the following error. I have added the file path into line 15 

fname = r'C:\Users\kirsl\Desktop\Pompei for MK\download.jpg' # let empty for test image

and the script returns this error:

PS C:\Users\kirsl\Downloads\mosaic-main\mosaic-main> python mosaic.py
Traceback (most recent call last):
  File "C:\Users\kirsl\Downloads\mosaic-main\mosaic-main\mosaic.py", line 12, in <module>
    import edges, guides, tiles, convex, coloring, plotting
  File "C:\Users\kirsl\Downloads\mosaic-main\mosaic-main\edges.py", line 4, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

I see the issue is with two modules, however I am at a loss for what to do to resolve these issues. Could somebody offer some guidance?

**Comment by JavierCoronel** [comment]
Hi, it seems you don't have bumpy installed. You can try `pip install numpy` on your console and run the code again

**Comment by AKVG** [comment]
Much appreciation for your help. 
I have really basic knowledge of how to use the code "mosaic" available here on github cited in this article:

https://towardsdatascience.com/how-to-generate-roman-style-mosaics-with-python-11d5aa021b09

I downloaded Python, have all the files noted downloaded in a file on my laptop, and after entering a file path in the code on line 15 and running this as a Project, experienced the two issues shown above including the numpy error. When you say (bumpy I think is a typo) try "pip install numpy" on my console, after googling that term, I'm not sure whether the NumPy 'package' is 
something I have to install, somehow, or what to do. 

Numpy.org's page: https://numpy.org/install/

on Installing NumPy advises:

If you use pip, you can install NumPy with:
pip install numpy

which I have no idea what to do. NumPy site links on their pages about pip go into building numpy, etc becomes a deep rabbithole. 

With all the files loaded into Python as a project (in opposed to however I managed to run mosiac.py last night) I get a yellow warning icon and text at the top of the code that says "Package requirement 'opencv>=3.4.3' is not satisfied (if that matters), and when trying to run it, the same script/error above. Can you elaborate what is needed to correct the issue/s? I thought the article and code would be straightforward to be able to use/run. I downloaded the most recent version of Python, 3.12.1 from Pytho.org.  Thank you!

**Comment by JavierCoronel** [comment]
Hi, I know that all this setup could be difficult to have ready for a clean running. Specially if you are just starting coding. 
I would be glad to help also if you explain a bit more how you are trying to run the code: are you using vscode, pycharm or some other text editor to modify the script and run it?

What you'll need to do first is install all the required packages (opencv, numpy, etc...). Even if you have python installed, you'll need these extra packages to execute the code. This you have to do it on a terminal/console (cmd or with the software you're running the code with). 
Once you have the terminal open, you can simply write `pip install numpy, opencv-python, scipy, scikit_learn` and hit enter to install those libraries.
After the packages are installed, you can proceed to execute the mosaic code.

Let me know how it goes, or if any other doubt, feel free to write to jd.coronel@outlook.com
